### PR TITLE
Use more concise way to get bytes

### PR DESCRIPTION
**Pull request by vayn**
We could use [withUnsafeBytes(_:)][1] in Swift 3 instead of long `unsafeBitCast`.

[1]: https://developer.apple.com/reference/foundation/data/1780450-withunsafebytes

### CODE REVIEW

**Comment by Econa77** [comment]
@Vayn Sorry for late reply. And thanks PullRequest.

When building the changed place, occurred `BAD_ACCESS `.
Would you please try it with the following code?

`AppDelegate.swift` in `Example.xcodeproj`
```
// ⌘ + Control + B
guard let keyCombo = KeyCombo(keyCode: 11, carbonModifiers: 4352) else { return }
print(keyCombo.characters) // Occurred BAD_ACCESS
```

**Comment by vayn** [comment]
Yes, I've compiled Example project for testing. It worked very well.

screenshot

Hmm I guess the crash may be caused by the old version of Xcode. My Xocde Version is `Version 8.1 (8B62)`.

**Comment by Econa77** [comment]
@Vayn Sorry for the delay in confirmation. I was able to build it 👍 
If you still feel like correcting it, can you rebase and resolve conflicts?

**Comment by Econa77** [comment]
Sorry. This code will be moved to Sauce (https://github.com/Clipy/Sauce) and will be deleted.
Thank you for the contribution 🙏

**Pull request closed without merging**
